# ingress-controller 설치 명령어
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.1/deploy/static/provider/aws/deploy.yaml
# aws lb -> ingress controller pod -> ingress -> service로의 라우팅

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ordersystem-ingress
  namespace: cho-ns
  annotations:
    kubernetes.io/ingress.class: nginx  
spec:
  tls:
  - hosts:
    - "server.chokanghyun.shop"
    secretName: server-chokanghyun-shop-tls
  rules:
  - host: server.chokanghyun.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-service
            port:
              number: 80