apiVersion: v1
kind: Service
metadata:
# 클러스터 내에서 service명은 url주소(엔드포인트)로 사용 ex)http://my-service:포트번호
  name: my-service
  namespace: cho-ns
spec:
# 타입:클러스터아이피는 디폴트라 생략가능
  type: ClusterIP
  ports:
  # port - 서비스의 port / targetPort - pod내 컨테이너의 port(내부포트)
  - port: 80
    targetPort: 80
    # selector.app - pod의 label과 일치되어야 매핑 됨
  selector:
    app: my-nginx